cam/urls.py
from django.conf import settings
from django.urls import path
from cam.views import camera_1,md,cap,Register,operation
from django.conf.urls.static import static


app_name='cam'

urlpatterns = [
    path('show/',camera_1,name='show'),
    path('cap/',cap,name='cap'),
    path('input/',Register,name='Register'),
    path('mod/',md,name='mod'),
    path('operation/',operation,name='operation'),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cam/', include('cam.urls')),
    path('', include('main.urls')),
    path('contact/', include('contact.urls')),
    path('member/', include('member.urls')),
]

contact/urls.py
from django.conf import settings
from django.urls import path
from contact.views import contact, search, detail
from contact.views import update, delete, answer_create, answer_delete
from contact.views import upload3, download
from django.conf.urls.static import static

app_name='contact'

urlpatterns = [
    path('contact/', contact, name="list"),
    path('search/', search, name='search'),
    path('<int:question_id>/', detail, name='detail'),
    path(
        'answer/create/<int:question_id>/', answer_create,
        name='answer_create'),
    path('<int:question_id>/update/', update, name="update"),
    path('<int:question_id>/delete/', delete, name="delete"),
    path('upload3/', upload3, name='upload3'),
    path('download/<int:question_id>/', download, name='download'),
    path('<int:answer_id>/answer_delete/', answer_delete, name="answer_delete"),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

firebase/firebase/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main/urls.py
from django.conf import settings
from django.urls import path
from main.views import index,about,chatanswer
from django.conf.urls.static import static

app_name='main'

urlpatterns = [
    path('',index,name='index'),
    path('about/',about,name='about'),
    path('chatanswer/', chatanswer, name="chatanswer")
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path
from . import views

app_name = 'member'

urlpatterns = [
  path('login/', views.login_view, name="login"),
  path('logout/', views.logout_view, name="logout"),
  path('signup/', views.signup, name='signup'),
]

cam/models.py
from django.db import models

# Create your models here.
class Photo(models.Model):
    names= models.CharField(max_length=200)

cam/views.py
from cv2 import CAP_DSHOW
import os
import cv2
from django.shortcuts import render,redirect
import numpy as np
from cam.models import Photo
from PIL import Image
from django.contrib.auth.decorators import login_required

def camera_1(request):
    rows = Photo.objects.all()
    names=[]
    for i in rows:
        names.append(i.names)
    l=len(names)
    return render(request, 'cam/camera.html',{'names':names,'l':l})
@login_required(login_url='member:login')
def Register(request):
    if request.method == "POST": 
        print(request.POST)
        names = request.POST.get("names")
        Photo.objects.create(names=names)  
        return redirect("cam:cap")
    return render(request, "cam/input.html")

directory= os.getcwd()
paths=directory+'/dataset/'
trainpath=directory+'/trainer/trainer.yml'
recognizer = cv2.face.LBPHFaceRecognizer_create()
detector = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")

if not os.path.exists(paths):
    os.makedirs(paths)

def cap(request):
    rows = Photo.objects.all()
    nums=rows.count()
    cam = cv2.VideoCapture(0+CAP_DSHOW)
    cam.set(3, 640) # set video width
    cam.set(4, 480) # set video height
    face_detector = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    path=directory+"/dataset/User."
    face_id = nums
    count = 0
    while(True):
        ret, img = cam.read()
        #img = cv2.flip(img, -1) 
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_detector.detectMultiScale(gray, 1.3, 5)
        for (x,y,w,h) in faces:
            cv2.rectangle(img, (x,y), (x+w,y+h), (255,0,0), 2)     
            count += 1
            cv2.imwrite(path + str(face_id) + '.' + str(count) + ".jpg", gray[y:y+h,x:x+w])
            cv2.imshow('image', img)
        k = cv2.waitKey(100) & 0xff 
        if k == 27:
            break
        elif count >= 50:
            break
    cam.release()
    cv2.destroyAllWindows()

    return redirect('cam:show')

def getImagesAndLabels(path):
    imagePaths = [os.path.join(path,f) for f in os.listdir(path)]     
    faceSamples=[]
    ids = []
    for imagePath in imagePaths:
        PIL_img = Image.open(imagePath).convert('L') 
        img_numpy = np.array(PIL_img,'uint8')
        id = int(os.path.split(imagePath)[-1].split(".")[1])-1
        faces = detector.detectMultiScale(img_numpy)
        for (x,y,w,h) in faces:
            faceSamples.append(img_numpy[y:y+h,x:x+w])
            ids.append(id)
    return faceSamples,ids
@login_required(login_url='member:login')
def md(request):
    faces,ids = getImagesAndLabels(paths)
    recognizer.train(faces, np.array(ids))
    recognizer.write(trainpath)
    recognizer.read(trainpath)
    cascadePath = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
    faceCascade = cv2.CascadeClassifier(cascadePath)
    font = cv2.FONT_HERSHEY_SIMPLEX

    id = 0
    rows = Photo.objects.all()
    names=[]
    for i in rows:
        names.append(i.names)

    while True:
        cam = cv2.VideoCapture(0+CAP_DSHOW)
        cam.set(3, 640) # set video widht
        cam.set(4, 480) # set video height

    # Define min window size to be recognized as a face
        minW = 0.1*cam.get(3)
        minH = 0.1*cam.get(4)
        ret, img =cam.read()
        img = cv2.flip(img, 1) # Flip vertically
        gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

        faces = faceCascade.detectMultiScale( 
            gray,
            scaleFactor = 1.2,
            minNeighbors = 5,
            minSize = (int(minW), int(minH)),
        )

        for(x,y,w,h) in faces:
            cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,0), 2)
            id, confidence = recognizer.predict(gray[y:y+h,x:x+w])

            if (confidence < 100):
                id = names[id]
                confidence = "  {0}%".format(round(100 - confidence))
            else:
                id = "unknown"
                confidence = "  {0}%".format(round(100 - confidence))

            cv2.putText(img, str(id), (x+5,y-5), font, 1, (255,255,255), 2)
            cv2.putText(img, str(confidence), (x+5,y+h-5), font, 1, (255,255,0), 1)  
        cv2.imshow('camera',img) 
        k = cv2.waitKey(10) & 0xff # Press 'ESC' for exiting video
        if k == 27:
            cam.release()
            cv2.destroyAllWindows()
            break
    return redirect('cam:show')

cam/templates/cam/camera.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MEDIPENSER-Camera</title>
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
  
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  
  
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
  
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
  </head>
 
<body>

  <style>
    @import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200&display=swap');
    
    .pt-5, .py-5 {
      padding-top: 0rem!important;
    }
    .mt-5, .my-5 {
      margin-top :2 rem!important;
    }
    footer { font-family: 'Nanum Gothic', sans-serif; }

    .floating 
    { position: fixed; right: 50%; 
      top: 600px; margin-right: -720px;
       text-align:center; width: 120px; }

    
       
    .modal-body::-webkit-scrollbar{ display:none; }

       
    .modal-dialog{position: fixed; 
      right: 50%; 
      top: 50px; margin-right: -520px;
       text-align:center; width: 800px; height: 800px;}

      .modal-body{max-height: calc(100vh - 210px);
       overflow-y: auto;-ms-overflow-style: none;}
    
  </style>
  <div class="site-wrap">
    <div class="site-navbar py-2">

      <div class="search-wrap">
        <div class="container">
          <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
          <form action="#" method="post">
            <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
          </form>
        </div>
      </div>

      <div class="container">
        <div class="d-flex align-items-center justify-content-between">
          <div class="logo">
            <div class="site-logo">
              <a href="{% url 'main:index' %}" class="js-logo-clone"><img src="{% static 'images/logo1.png' %}" width='200'></a>
            </div>
          </div>
          <div class="main-nav d-none d-lg-block">
            <nav class="site-navigation text-right text-md-center" role="navigation">
              <ul class="site-menu js-clone-nav d-none d-lg-block">
                <li><a href="{% url 'main:index' %}">Home</a></li>
                <li class="active"><a href="{% url 'cam:show' %}">Camera</a></li>
                <li><a href="{% url 'main:about' %}">UserPage</a></li>
                <li><a href="{% url 'contact:list' %}">Contact</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'member:login' %}">Logout</a></li>
                {%else%}
                <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
              <script>
                const swalWithBootstrapButtons = Swal.mixin({
                  customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                  },
                  buttonsStyling: false
                })
                
                swal.fire({
                  title: '먼저 로그인 해주세요',
                  text: "메디펜서의 모든 서비스를 이용할 수 있습니다",
                  icon: 'warning',
                  showCancelButton: true,
                  allowOutsideClick:false,
                  confirmButtonColor: '#2BADE4',
                  cancelButtonColor: '#F47957',
                  confirmButtonText: '확인',
                  cancelButtonText: '취소'
                }).then((result) => {
                  if (result.isConfirmed) {window.location.href = "{% url 'member:login' %}";
                  }
                  else if (
                  result.dismiss === Swal.DismissReason.cancel) {window.location.href = "{% url 'main:index' %}";
                }
               
                });
                
              </script>
                <li><a href="{% url 'member:login' %}">Login</a></li>
                {%endif%}
              </ul>
            </nav>
          </div>
          <div class="icons">
            <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none"><span
                class="icon-menu"></span></a>
          </div>
        </div>
      </div>
    </div> 

<!--네비게이션 END -->

    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0"><a href="{% url 'main:index' %}" ><span style="color:#86DACA">Home</span></a> <span class="mx-2 mb-0">/</span> <strong
              class="text-black">Camera</strong></div>
        </div>
      </div>
    </div>
    
    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="#86DACA" class="bi bi-camera-fill" viewBox="0 0 16 16">
              <path d="M10.5 8.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
              <path d="M2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2zm.5 2a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm9 2.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0z"/>
            </svg>
            <article class="templatemo-item">
             
{% comment %}               
              <h2>여기를 보세요</h2> {% endcomment %}
              {%if l is 0 %}
              <h3>환자를 등록해주세요</h3>
            {%else%}
            <h3>등록된 환자: {{names}}</h3>
            {%endif%}
              <p>
               {% comment %} <img src="{% url 'cam:cap' %}" alt=""></br></br>	 {% endcomment %}
              </p>
      
            </article><hr> 
              </br>
              <p>
                <div class="btn_wrap">
                  <form action="{% url 'cam:Register' %}">
                  <button type="submit" class="btn btn-light" style='background-color:#86DACA'><span style='color:grey;font-weight:bold'>등록하기</span>
                </button></p></form>
              <div class="btn_wrap">
                <form action="{% url 'cam:mod' %}">
           <button type="submit" class="btn btn-light" style='background-color:#86DACA'><span style='color:grey;font-weight:bold'>인식하기</span></button></p>
                </form>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% comment %} 챗봇 시작 {% endcomment %}
<div class='floating'><a href=# data-toggle="modal" data-target="#myModal"><img src="{% static 'images/chat1.png' %}" width='100'></a></div>
<div class="modal fade" id="myModal" role="dialog"> 
 <div class="modal-dialog"> 
   <div class="modal-content" style="background-color:#BAD3D2;color:black;"> 
     <div class="modal-header">
        <h4 class="modal-title">메디봇</h4> <button type="button" class="close" data-dismiss="modal">×</button> 
       </div> <div id="chatbox"class="modal-body" style="height:450px;margin-top:50px;padding:10px;background-color:#BAD3D2;overflow-y:scroll;overflow-x:hidden;max-height:100vh;color:black">안녕하세요.저는 메디봇이에요! 저에게 질문을 해주세요! </div>
       <div class="chatfooter">
         <table width="100%">
             <tr>
             <td width="90%">
                 <input id="chattext" placeholder="질문을 입력하고 엔터키를 눌러주세요" style="padding:5px 0;width:100%;border:solid;color:grey;font-weight:bold;">
             </td>
             <td width="10%"><button class="btn btn-secondary" style="padding:5px 0;width:100%;background-color:#86DACA" onclick="sendAsk()" id="sendbtn"><span style='color:grey;font-weight:bold'>입력</span></button></td>
             </tr>
         </table>
     </div>
          </div> 
         <div class="modal-footer"> 
         
           </div>
         
       </div> 
     </div> 
   </div>

   {% block scripts %}
   <script>
   function getCookie(name) {
       var cookieValue = null;
       if (document.cookie && document.cookie !== '') {
           var cookies = document.cookie.split(';');
           for (var i = 0; i < cookies.length; i++) {
               var cookie = jQuery.trim(cookies[i]);
       
               if (cookie.substring(0, name.length + 1) === (name + '=')) {
                   cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                   break;
               }
           }
       }
       return cookieValue;
   }

   var csrftoken = getCookie('csrftoken');

   var xhr;

   function sendAsk() {
       chattext = document.getElementById("chattext").value;
       if(chattext == "") {
           document.getElementById("chattext").focus();
           return false;
       }

       addtext = "<div style='margin:15px 0;text-align:right;'> <span style='padding:3px 15px;background-color:#86DACA;border-radius:3px;'>" + chattext + "</span></div>";
       document.getElementById("chatbox").innerHTML += addtext;

       var strurl = "{% url 'main:chatanswer' %}?questext=" + chattext;
       //alert(strurl);
       //return false;

       xhr = new XMLHttpRequest();
       xhr.onreadystatechange = function() {
           if (xhr.readyState == 4) {
               var data = xhr.responseText;

               var obj = JSON.parse(data);

               if(obj.flag == "0"){

                   bottext = "<div style='margin:15px 0;text-align:left;'><span style='padding:3px 15px;background-color:white;border-radius:3px;'>" + obj.anstext + "</span></div>";
                   document.getElementById("chatbox").innerHTML += bottext;

                   var objDiv = document.getElementById("chatbox");
                   objDiv.scrollTop = objDiv.scrollHeight;

                   document.getElementById("chattext").value = "";
                   document.getElementById("chattext").focus();

               }
           }
       };
       xhr.open("GET", strurl);
       xhr.setRequestHeader("X-CSRFToken", csrftoken);
       xhr.send(null);
   }

 

   </script>
{% endblock %}
<script>

 var input = document.getElementById("chattext");
 
 input.addEventListener("keyup", function(event) {
   if (event.keyCode === 13) {
     document.getElementById("sendbtn").click();
   }
 });
 
 </script>
{% comment %} 챗봇 끝 {% endcomment %}

    <footer class="site-footer" style="background-color:#c6eee6; padding:3em 0;">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-lg-3 mb-4 mb-lg-0" style="margin-right:120px;">

            <div class="block-7">
              <h3 class="footer-heading mb-4">About Us</h3>
              <p style="color:#25262a;">'MEDIPENSER'는 치매나 지적장애인 등 보호가 필요한
                사람들에게 올바른 약을 복용할 수 있도록 얼굴인식을 기반으로 한 AI 서비스입니다.
              </p>
            </div>

          </div>
          <div class="col-lg-3 mx-auto mb-5 mb-lg-0">
            <h3 class="footer-heading mb-4">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="{% url 'cam:show' %}">CAMERA</a></li>
              <li><a href="{% url 'main:about' %}">USERPAGE</a></li>
              <li><a href="{% url 'contact:list' %}">CONTACT</a></li>
              
            </ul>
          </div>

          <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
              <h3 class="footer-heading mb-4">Contact Info</h3>
              <ul class="list-unstyled">
                <li class="address">㈜케이티 대전 서구 탄방동 649 </li>
                <li class="phone"><a href="tel://0421234567">042 123 4567</a></li>
                <li class="email">medipenser@MEDIPENSER.com</li>
              </ul>
            </div>


          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;
              <script>document.write(new Date().getFullYear());</script> MEDIPENSER<i class="icon-heart" aria-hidden="true"></i> 
             <!-- by <a href="https://colorlib.com" target="_blank"
                class="text-primary">Colorlib</a>. Downloaded from <a href="https://themeslab.org/" target="_blank">Themeslab</a> -->
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
          </div>

        </div>
      </div>
    </footer>
  </div>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>

  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

cam/templates/cam/control.html
<html>
	<head> 
	<!--
		공대선배 라즈베리 파이썬 #20 웹사이트의 버튼, 슬라이더 바를 이용해 서보모터를 제어하는 코드 html 파일
		채널 주소 : https://www.youtube.com/channel/UCsiwB64NJe1JYFZ6iUeFQqA
	-->
    <!--title은 브라우저 맨 위(제목표시줄)에 나오는 내용을 결정-->
	<title>SERVO CONTROLLER</title>	
	<meta name="viewport" content="width=device-width initial-scale=1">
	</head> 
	<body>
		<!--본문 시작. h1은 가장 큰 글씨로 글자를 써줌-->
		<h1>Web에서 라즈베리파이의 서보모터 제어하기</h1>
		<!--hr은 수평 가로줄을 그려줌-->
        <hr>

		<div style="padding-left:20px;">
        <!--h3는 중간크기 글씨로 글자를 써줌-->
			<h3>서보모터 제어</h3>
                <!--
					html에서 파이썬으로 변수값을 보낼때, GET, POST 두가지 방식중 하나를 사용해서 넘겨줌
					여기서는 GET 방식을 사용함. 또한 변수값 전송은 form 형태로 만들어둬야 함
					또한 action="/servo_control"로 해두면, 해당 주소에서 변수를 요청해야 값을 넘겨줌
					복잡한 사이트에서 혼동을 방지하기 위한 것(사용자1용 페이지에서 사용자 2의 변수값을 요구할 수 없음) 
					아래 두개는 버튼으로 각각 현재각도+10, -10을 해주는 것
					같은 함수를 사용하기 때문에 주소를 따로 나누지 않아도 됨
				-->
				<form method="GET" action="/servo_control">
						<input type="range" min="0" max="180" name="deg" value={{deg}} onchange="this.form.submit()"/> 		
				</form>
				<a href="{{ url_for('servo_control', deg=deg+10) }}"><input type="button" value="+10" ></a>
				<a href="{{ url_for('servo_control', deg=deg-10) }}"><input type="button" value="-10" ></a>
				각도 : {{deg}}
            <hr>
		</div>
	</body>
</html>

cam/templates/cam/input.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MEDIPENSER</title>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <style>
    @import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200&display=swap');
    body {
      min-height: 100vh;
      font-family: 'Noto Sans KR', sans-serif;
      background:  -webkit-gradient(linear, left bottom, right top, from(#bad3c0), to(#CFEBEA));
      /* background: -webkit-linear-gradient(bottom left, #bad3c0 0%, #CFEBEA 100%);
      background: -moz-linear-gradient(bottom left, #bad3c0 0%, #CFEBEA 100%);
      background: -o-linear-gradient(bottom left, #bad3c0 0%, #CFEBEA 100%);
      background: linear-gradient(to top right, #bad3c0 0%, #CFEBEA 100%); */
    }

    .input-form {
      max-width: 680px;

      margin-top: 80px;
      padding: 32px;

      background: #fff;
      -webkit-border-radius: 10px;
      -moz-border-radius: 10px;
      border-radius: 10px;
      -webkit-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);
      -moz-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);
      box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15)
    }

    #btn-1 {
      border:none;
    }

    p {
      line-height: 50%;
    }
  </style>
</head>

<body>
  <form method="post" class="post-form">
    {% csrf_token %}
  <div class="container">
    <div class="input-form-backgroud row">
      <div class="input-form col-md-12 mx-auto">
        <h4 class="mb-3" style="text-align: center;">등록</h4>
        <form class="validation-form" novalidate>
          {% comment %} <div class="row">
            <div class="col-md-12 mb-3">
              <label for="number">번호</label>
              <input type="number" class="form-control" id="number" name = "number" placeholder="번호를 입력해주세요" value="" required>
            </div>
          </div> {% endcomment %}

          <div class="mb-3">
            <label for="name">이름</label>
            <input type="names" class="form-control" id="names" name = "names"placeholder="이름을 영문으로 입력해주세요" required>
            <div class="mb-3" >
              <br>
                <button id="btn-1" class="btn btn-primary btn-lg btn-block float-left" type="submit" style=" background-color: #b0ddb6; height:45px;width:100px;">
                  완료</button></div>
 
          </div>
        </form>

      
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/aos.js' %}"></script>
      
        <script src="{% static 'js/main.js' %}"></script>
      
      </body>
      
      </html>