cam/urls.py
from django.conf import settings
from django.urls import path
from cam.views import camera_1,md,cap,Register,operation
from django.conf.urls.static import static


app_name='cam'

urlpatterns = [
    path('show/',camera_1,name='show'),
    path('cap/',cap,name='cap'),
    path('input/',Register,name='Register'),
    path('mod/',md,name='mod'),
    path('operation/',operation,name='operation'),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cam/', include('cam.urls')),
    path('', include('main.urls')),
    path('contact/', include('contact.urls')),
    path('member/', include('member.urls')),
]

contact/urls.py
from django.conf import settings
from django.urls import path
from contact.views import contact, search, detail
from contact.views import update, delete, answer_create, answer_delete
from contact.views import upload3, download
from django.conf.urls.static import static

app_name='contact'

urlpatterns = [
    path('contact/', contact, name="list"),
    path('search/', search, name='search'),
    path('<int:question_id>/', detail, name='detail'),
    path(
        'answer/create/<int:question_id>/', answer_create,
        name='answer_create'),
    path('<int:question_id>/update/', update, name="update"),
    path('<int:question_id>/delete/', delete, name="delete"),
    path('upload3/', upload3, name='upload3'),
    path('download/<int:question_id>/', download, name='download'),
    path('<int:answer_id>/answer_delete/', answer_delete, name="answer_delete"),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

firebase/firebase/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

contact/models.py
from django.db import models


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField()
    username = models.CharField(max_length=200)
    file = models.FileField(null=True, blank=True)

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    username = models.CharField(max_length=200)

contact/forms.py
from django import forms
from .models import Question, Answer

class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ['subject', 'content', 'file']
       
        labels = {
            'subject': '제목',
            'content': '내용',
   
        }
        def __init__(self, *args, **kwargs):
            super(QuestionForm, self).__init__(*args, **kwargs)
            self.fields['file'].required = False


class AnswerForm(forms.ModelForm):
    
    class Meta:
        model = Answer
        fields = ['content']
        labels = {'content': '답변내용',}

contact/views.py
import os
import urllib
import mimetypes
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Question, Answer
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from member.models import User


def contact(request):
    now_page = request.GET.get('page', 1)
    question_list = Question.objects.order_by('-pub_date')
    p = Paginator(question_list, 10)
    info = p.get_page(now_page)
    start_page = (int(now_page) - 1) // 10 * 10 + 1
    end_page = start_page + 9
    if end_page > p.num_pages:
        end_page = p.num_pages

    context = {'info': info,
        'page_range' : range(start_page, end_page + 1)}
    return render(request, 'contact/contact.html', context)


def search(request):
    if request.method == 'POST':
        search = request.POST.get('search')
        result=Question.objects.filter(subject__contains=search)
        return render(
                request,
                'contact/show.html',
                {'data':result, 
                'search':search}
            )


def detail(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    context = {
        'question': question
    }
    return render(request, 'contact/contact_detail.html', context)


from .forms import AnswerForm
@login_required(login_url='member:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.username = request.user.username
            answer.save()
            return redirect('contact:detail', question_id=question.id)
    else:
        form = AnswerForm()
    
    context = {'question': question, 'form': form}
    
    return render(request, 'contact/contact_detail.html', context)


from .forms import QuestionForm
@login_required(login_url='member:login')
def upload3(request):
    user = User.objects.get(username = request.user.username)   
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
             
        if form.is_valid():
            uploadFile = form.save(commit=False)
            if uploadFile.file:        
                name = uploadFile.file.name 
                size = uploadFile.file.size                              
            uploadFile.pub_date = timezone.now()
            uploadFile.username = request.user.username
            uploadFile.save()
            user.save()
            return redirect('contact:list')
    else:
        form = QuestionForm()
    return render(
        request, 'contact/contact_form.html', {'form': form})


def update(request, question_id):
    question = Question.objects.get(id=question_id)
    if(question.username == request.user.username):
        if request.method == "POST":
            question.subject = request.POST['subject']
            question.content = request.POST['content']
            question.pub_date = timezone.now()
            
            question.save()
            return redirect('contact:list')
        else:
            question=Question()
            return render(request, 'contact/update.html', {'question':question})
    else :
        return render(request, 'contact/warning.html')


def delete(request, question_id):
    question = Question.objects.get(id=question_id)
    if(question.username == request.user.username):
        question.delete()
        return redirect('contact:list')
    return render(request, 'contact/warning.html')


def answer_delete(request,answer_id):
    comment = Answer.objects.get(id=answer_id)
    if(comment.username == request.user.username):
        comment.delete()
        return redirect('contact:list')
    return render(request, 'contact/warning.html')



def download(request,question_id):   
    question = get_object_or_404(Question, pk=question_id)
    if question.file:
        url = question.file.url[1:] 
        file_url = urllib.parse.unquote(url)
        if os.path.exists(file_url) :
            with open(file_url, 'rb') as fh:
                quote_file_url = urllib.parse.quote(file_url.encode('utf-8'))
                response = HttpResponse(fh.read(), content_type=mimetypes.guess_type(file_url)[0])
                response['Content-Disposition'] = 'attachment; filename*=UTF-8\'\'%s' % quote_file_url
                return response
    else :  
        return render(request, 'contact/delete.html')

contact/templates/contact/contact.html
{% extends 'base.html' %}


<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}

<title>Contact &mdash; List </title>


<div class="container">

    <br><br>
    <table class="table table-striped">

        <div id="board-search">
            <div class="container">
                <div class="search-window">
                    <form method="post" action="{% url 'contact:search' %}">
                        {% csrf_token %}
                        <div class="search-wrap">
                            <input type="text" name="search" placeholder="검색어를 입력해주세요." value="">
                            <button type="submit" class="btn btn-dark">검색</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>



    </div>
        <br>

        <thead class="thead-primary">
            <tr>

                <b>
                    <th scope="col" class="th-num">번호</th>
                    <th scope="col" class="th-title">제목</th>
                    <th scope="col" class="th-date">작성자</th>
                    <th scope="col" class="th-date">작성일지</th>

            </tr>
        </thead>
        <tbody>
            {% if info %}

            {% for question in info %}
            <tr>

                <td>{{ forloop.revcounter }}</td>
                <td>
                    <a href="{% url 'contact:detail' question.id %}">
                        <span style='color:black'>{{ question.subject }}</span>
                    </a>
                </td>
                <td>
                    {{question.username}}
                </td>
                <td>{{ question.pub_date }}</td>
            </tr>

            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">게시글이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    
    <div class="d-grid gap-2 d-md-block">
        
        <a href="{% url 'contact:upload3' %}" class="btn btn-light btn-sm float-right" style='background-color:#86DACA'>
            <h6><span style='color:grey;font-weight:bold'>작성하기</h6></span>
        </a>
</div>


<br><br>
<div class="d-grid gap-2 col-2 mx-auto">
    <div style='text-align:right;'>
        <ul class='pagination'>
            {% for i in page_range %}
            <li class="page-item">
                <a class="page-link" href='{% url "contact:list" %}?page={{ i }}'>
                    {{ i }}
                </a>
            </li>

            {% endfor %}
        </ul>
    </div>
</div>

</div>
<br><br>
</div>

{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->


</body>

</html>

contact/templates/contact/contact_detail.html
{% extends 'base.html' %}
      

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}

<div class="container my-3">
    <br>
  
    <br>

    <h3 class="border-bottom py-2">  <img src="/static/images/q.png"> <b>{{ question.subject }}</b>
        <br></h3>
     
        <div class="card shadow mb-4" >
            <div class="card-header py-3"  >
                <b style='color: #000000'>
                      작성자 ID : <b>{{question.username}}</b>
                      <div style="float:right;" class="badge badge-light p-2" >
                        {{ question.pub_date }}
                    </div>
                    
            </div>
            {%if question.file  %}
            <div style="text-align:center;">
                <img src="{{question.file.url}}" width="600" height='300'><br>
            </div>
            {%endif%}
                <div class="card-text" style="white-space: pre-line;">
                    　{{ question.content }}
                </div>
                <div class="card-body">
                <div class="d-flex justify-content-end">
                    <div class="form-group">
                        <a href="{% url 'contact:list' %}" class="btn btn-light" style='background-color:#86DACA'><span style='color:grey;font-weight:bold'>
                            목록으로</span>
                        </a>
                        <a href="{% url 'contact:download' question.id %}" class="btn btn-light" style='background-color:#86DACA'><span style='color:grey;font-weight:bold'>
                            다운로드</span></a>           
                        <a href="{% url 'contact:update' question.id %}" class="btn btn-light" style='background-color:#86DACA'>
                            <span style='color:grey;font-weight:bold'>수정</a></span>
                        <a href="{% url 'contact:delete' question.id %}" class="btn btn-light" style='background-color:#86DACA'>
                            <span style='color:grey;font-weight:bold'>삭제</span></a>
                    </div>
                
                </div>
            </div>
        </div>

       
    <br>
   <h4 class="border-bottom my-2 py-2" style='color:#8C92A0'>
        <div><img src="/static/images/a.png"><b>
            등록된 답변</div>
    </b></h4>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"> <span style="color: black">{{question.answer_set.count}}개의 답변</h6></span>
        </div>
        <div class="card-body">
        
            <div>
                
            </div>

    {% for answer in question.answer_set.all %}
    <div class="card shadow mb-4">
        <div class="card-header py-3" >
            <b style='color: #EF8161'>
                작성자 : {{ answer.username }} </b>
                <a href="{% url 'contact:answer_delete' answer.id %}" class="btn btn-light" style='background-color:#86DACA;float:right;color:grey;font-weight:bold' onClick="alert('삭제되었습니다.')">삭제</a>
        </div>
        
            <div class="card-text" style="white-space: pre-line;">
                　 {{ answer.content }}
            </div>
            <div class="card-body">
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2" style='background-color:white'>


                    {{ answer.create_date }}
                    <br><br>
               
                </div>
                
            </div>
        </div>
    </div>
    {% endfor %}
    
    
    <form action="{% url 'contact:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}

        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->

       
            <textarea name="content" id="content" class="form-control" rows="7" placeholder="내용을 입력해주세요"></textarea>
        </div>
        <div style='text-align:center;'>
            <input type="submit" value="답변등록" class="btn btn-light" style='color:grey;font-weight:bold;background-color:#86DACA'>
        </div>
    </form>
    <div>
       
        </form>
       
     </div>
    <br><br>
    </div>
</div>
</div>
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

</body>

contact/templates/contact/contact_form.html
{% extends 'base.html' %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2"><span
            style="background: linear-gradient(to top, #86DACA 10%, transparent 20%);color:black">질문 등록</h5></span>
    <form class="post-form my-3" action="{% url 'contact:upload3' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- 오류표시 Start -
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
         오류표시 End -->

        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" placeholder="제목을 입력해주세요"
                value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>


            <textarea name="content" id="content" class="form-control" rows="10" placeholder="내용을 입력해주세요"></textarea>

            <br>


            <input type="file" name="file">

        </div>
        <div style='text-align:right;'>
            <br><button type="submit" class="btn btn-light" style='background-color:#86DACA'><span style='color:grey;font-weight:bold'>저장하기</span></button>
            <a href="{% url 'contact:list' %}" class="btn btn-light"style='background-color:#86DACA'>
                <span style='color:grey;font-weight:bold'>목록으로</span>
            </a>
        </div>
        <br> <br> <br>
    </form>

</div>

{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

</body>

contact/templates/contact/contact_form2.html
{% extends 'base.html' %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form class="post-form my-3" action="{% url 'board:upload3' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- 오류표시 Start -
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
         오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>


            <textarea name="content" id="content" class="form-control" rows="10" placeholder="내용을 입력해주세요"></textarea>

            <input type="file" name="file">

        </div>
        <div style='text-align:right;'>
            <br><button type="submit" class="btn btn-light" style='background-color:#86DACA'><span style='color:grey;font-weight:bold'>저장하기</span></button>
            <a href="{% url 'board:index' %}" class="btn btn-light" style='background-color:#86DACA'>
                <span style='color:grey;font-weight:bold'> 목록으로</span>
            </a>
        </div>
    </form>
</div>

{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

</body>

contact/templates/contact/delete.html
<script>
    alert("파일이 없습니다.")
    window.history.back() 
</script>

contact/templates/contact/show.html
{% extends 'base.html' %}


<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}

<title>Contact &mdash; Search </title>

<div style="text-align:center">
    <h3 class="heading-section">"<mark>{{search}}</mark> "포함된 검색결과입니다.</h3>
    <br>
 </div>

<div class="container">
    
    <table class="board-table">
        <thead class="thead-primary">
            <tr>
                    <b><th scope="col" class="th-num">번호</th>
                    <th scope="col" class="th-title">제목</th>
                    <th scope="col" class="th-date">작성자</th>
                    <th scope="col" class="th-date">작성일지</th>
            </tr>
        </thead>
        <tbody>
                {% for item in data %}
                <tr>
                    <td> {{ item.id }}</td>
                    <td>
                    <a href="{% url 'contact:detail' item.id %}">
                        {{ item.subject }}
                    </a>
                    </td>   
                    <td> {{item.username}}</td>
                    <td>{{item.pub_date}}</td>    
                   
                </tr>   
                {% endfor %}
            <tr>   
        </tr>
        </tbody>
        </table>
        <div style='text-align:center;'>
            <ul class='pagination'>
                {% for i in page_range %}
                <li>
                <a href='{% url "contact:list" %}?page={{ i }}'>
                    {{ i }}
                </a>
                </li>
                {% endfor %}
                </ul>
            </div>
        
        <br><br>
    </div>

{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

</body>

contact/templates/contact/update.html
{% extends 'base.html' %}


<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시물 수정</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea name="content" id ="content" class="form-control" rows="10"
            placeholder = "내용을 입력해주세요"></textarea> 
        <div style='text-align:right;'>
            <br><button type="submit" class="btn btn-light" style='background-color:#86DACA'><span style='color:grey;font-weight:bold'>수정하기</span></button>
            <a href="{% url 'contact:list' %}" class="btn btn-light" style='background-color:#86DACA'>
                <span style='color:grey;font-weight:bold'> 목록으로</span>
            </a>
        </div>
        </form>
        </div>
    </div>
</div>

{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

    </body>

contact/templates/contact/warning.html
<script>
    alert("권한이 없습니다.")
    window.history.back() 
</script>