cam/urls.py
from django.conf import settings
from django.urls import path
from cam.views import camera_1,md,cap,Register,operation
from django.conf.urls.static import static


app_name='cam'

urlpatterns = [
    path('show/',camera_1,name='show'),
    path('cap/',cap,name='cap'),
    path('input/',Register,name='Register'),
    path('mod/',md,name='mod'),
    path('operation/',operation,name='operation'),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cam/', include('cam.urls')),
    path('', include('main.urls')),
    path('contact/', include('contact.urls')),
    path('member/', include('member.urls')),
]

firebase/firebase/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main/urls.py
from django.conf import settings
from django.urls import path
from main.views import index,about,chatanswer
from django.conf.urls.static import static

app_name='main'

urlpatterns = [
    path('',index,name='index'),
    path('about/',about,name='about'),
    path('chatanswer/', chatanswer, name="chatanswer")
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path
from . import views

app_name = 'member'

urlpatterns = [
  path('login/', views.login_view, name="login"),
  path('logout/', views.logout_view, name="logout"),
  path('signup/', views.signup, name='signup'),
]

member/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# from phonenumber_field.modelfields import PhoneNumberField
# from django.core.validators import RegexValidator

class User(AbstractUser):

    fullname = models.CharField(max_length=50)
    age = models.CharField(max_length=50)
    gender = models.CharField(max_length=50)
    parmacy = models.CharField(max_length=50)
    relation = models.CharField(max_length=80, null=True)
    phone = models.CharField(max_length=50)
    password2 = models.CharField(max_length=50)

member/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import User
from django.contrib.auth import authenticate, login, logout

 

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username, password = password)
        if user is not None:
            print("인증성공")
            login(request, user)
            return redirect('main:index')
        else:
            print("인증실패")    
    return render(request, "login.html")
        

def signup(request):
    if request.method == "POST": # 요청메시지가 post 라면
        print(request.POST)
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        password2 = request.POST.get("password2")
        if password != password2 :
            return HttpResponse('비밀번호가 다릅니다.')
        fullname = request.POST.get("fullname")
        age = request.POST.get("age")
        gender = request.POST.get('gender')
        phone = request.POST.get("phone")
        parmacy = request.POST.get("parmacy")
        relation = request.POST.get("relation")
        

        user = User.objects.create_user(username, email, password)
        user.fullname = fullname
        user.password2 = password2
        user.age = age
        user.gender = gender
        user.phone = phone
        user.parmacy = parmacy
        user.relation = relation
        user.save()

        
        return redirect("member:login")

    return render(request, "signup.html")


def logout_view(request):
    logout(request)
    return redirect("member:login")

member/templates/form_errors.html
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<!-- 필드 오류를 출력한다. -->
<div class="alert alert-danger">
    <strong>{{ field.label }}</strong>
    {{ error }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<!-- 넌필드 오류를 출력한다. -->
<div class="alert alert-danger">
    <strong>{{ error }}</strong>
</div>
{% endfor %}
{% endif %}

member/templates/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MEDIPENSER-login</title>
 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    <style>

        @import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200&display=swap');
        
        * {margin:0; padding:0; box-sizing: border-box;}
        body {
          font-family: 'Noto Sans KR', sans-serif;
          display:flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
          background-color: #CFEBEA;
        
        }
        
        body::before {
          content: "";
          position: absolute; z-index:1;
          top:0; right:0; bottom:0; left:0;
          background-color: rgba(0, 0, 0, 0.1);
        }
        
        .login-form {position:relative; z-index:2;}
        .login-form h1{
          font-size: 32px; color: #fff;
          text-align: center;
          margin-bottom: 60px;
        }
        .int-area {
          width: 400px; position:relative;
          margin-top: 20px;
        }
        .int-area:first-child {margin-top:0;}
        .int-area input {
          width: 100%;
          padding: 20px 10px 10px;
          background-color: transparent;
          border:none;
          border-bottom: 1px solid #999;
          font-size: 18px; color:#fff;
          outline: none;
        }
        #btn-1{
          margin-left:75px
        }
        #btn-2{
          margin-right:75px
        }
        .int-area label {
          position: absolute; left:10px; top:15px;
          font-size: 18px; color: #999;
          transition: all .5s ease;
        }
        
        
        .int-area input:focus +label,
        .int-area input:valid + label {
          top:0;
          font-size:13px; color:#8e8e8e;
        }
        
        .btn-area {margin-top:30px;}
        .btn-area button {
          width: 100%; height: 50px;
          background: rgba(117, 117, 117, 0.5);
          /* background: #CFEBEA; */
          color:#fff;
          font-size: 20px;
          border:none;
          border-radius: 25px;
          cursor:pointer;
        }
        
        .caption {
          margin-top: 20px;
          text-align: center;
        }
        
        .caption a {
          font-size: 15px; color:#999;
          text-decoration: none;
          cursor:pointer;
        }
        </style>

       

    <section class="login-form">
     <h1> <a href="{% url 'main:index' %}" style="text-decoration:none ;color:white">MEDIPENSER</a></h1>
        {% if user.is_authenticated %}
        로그아웃 페이지   
        <h3>{{user.username}} 님 정말 로그아웃 하시겠어요?</h3>
        <div class="mb-3" style="float:left;">
          <br><br>
          <button id="btn-1" class="btn btn-lg btn-block" type="button" onclick = "location.href= '{% url 'member:logout' %}'" style="background-color: rgba(117, 117, 117, 0.5); width:150px;"><span style="color:white">확인</span></button></div>
          <div class="mb-3" style="float:right;">
            <br><br>
          <button id="btn-2" class="btn btn-lg btn-block" type="button" onclick = "location.href= '{% url 'main:index' %}'" style="background-color: rgba(117, 117, 117, 0.5); width:150px;"><span style="color:white">취소</span></button></div>
          {% else %}
          <form method="post" action="{% url 'member:login' %}">
          {% csrf_token %}
          
            <div class="int-area">
                <input type="username" name="username" id="username"
                autocomplete="off" required>
                <label for="username">USER NAME</label>
            </div>
            <div class="int-area">
                <input type="password" name="password" id="password"
                autocomplete="off" required>
                <label for="password">PASSWORD</label>
            </div>
            <div class="btn-area">
              <button type="submit" class="btn lg-12 ml-5">로그인</button>
            </div>
        </form>

        <div class="caption">
          <a href="{% url 'member:signup' %}" class="open-popup" style="font-weight:bold; font-size:20px">회원가입</a>
      </div>
        
    </section>
    {% endif %}


  

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

member/templates/signup.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MEDIPENSER-signup</title>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <style>
    @import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200&display=swap');
    body {
      min-height: 100vh;
      font-family: 'Noto Sans KR', sans-serif;
      background:  -webkit-gradient(linear, left bottom, right top, from(#bad3c0), to(#CFEBEA));
      /* background: -webkit-linear-gradient(bottom left, #bad3c0 0%, #CFEBEA 100%);
      background: -moz-linear-gradient(bottom left, #bad3c0 0%, #CFEBEA 100%);
      background: -o-linear-gradient(bottom left, #bad3c0 0%, #CFEBEA 100%);
      background: linear-gradient(to top right, #bad3c0 0%, #CFEBEA 100%); */
    }

    .input-form {
      max-width: 680px;

      margin-top: 80px;
      padding: 32px;

      background: #fff;
      -webkit-border-radius: 10px;
      -moz-border-radius: 10px;
      border-radius: 10px;
      -webkit-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);
      -moz-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);
      box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15)
    }

    #btn-1 {
      border:none;
    }

    p {
      line-height: 50%;
    }
  </style>
</head>

<body>
  <form method="post" class="post-form">
    {% csrf_token %}
  <div class="container">
    <div class="input-form-backgroud row">
      <div class="input-form col-md-12 mx-auto">
        <h4 class="mb-3" style="text-align: center;">회원가입</h4>
        <form class="validation-form" novalidate>
          <div class="row">
            <div class="col-md-12 mb-3">
              <label for="username">ID</label>
              <input type="username" class="form-control" id="username" name = "username" placeholder="ID를 입력해주세요" value="" required>
            </div>
          </div>

          <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" id="password" name = "password"placeholder="비밀번호를 입력해주세요" required>
            
          </div>

          <div class="mb-3">
            <label for="password2">비밀번호(확인)</label>
            <input type="password" class="form-control" id="password2" name="password2" placeholder="비밀번호를 입력해주세요" required>
          </div>

          <div class="mb-3">
            <label for="fullname">이름</label>
            <input type="fullname" class="form-control" id="fullname" name="fullname" placeholder="이름을 입력해주세요" required>
          </div>

          <div class="mb-3">
            <label for="phone">전화번호</label>
            <input type="phone" class="form-control" id="phone" name="phone" placeholder="전화번호를 입력해주세요" required>
          </div>

          <div class="mb-3">
            <label for="age">나이</label> 
            <input type="age" class="form-control" id="age" name="age" ageplaceholder="나이를 입력해주세요" value="" required>
          </div>

         <div class="mb-3">
            <label for="email">이메일</label> 
            <input type="email" class="form-control" id="email" name="email" ageplaceholder="이메일를 입력해주세요" value="" required>
          </div>

          <div class="mb-3">
            <label for="gender">성별</label> 
                    <label><input type="radio" name="gender" id="gender" value="male">남성</label>       <label><input type="radio" name="gender" id="gender" value="female">여성</label>
          </div>

          <div class="mb-3">
            <label for="relation" class="text-black">환자와의 관계(Relation) <span class="text-danger" name="relation" id="relation"></span></label>
            
    
            <select id="relation" class="form-control" name='relation'>
                <option selected>환자와의 관계</option>
                <option value = "부모">부모</option>
                <option value = "배우자">배우자</option>
                <option value = "자녀">자녀</option>
                <option value = "형제">형제</option>
                <option value = "간병인">간병인</option>
                <option value = "친인척">친인척</option>
            </select>
        </div>
        <br>
          <div class="mb-3">
            <label for="parmacy">주 이용 병원/약국(선택)</label>
            <input type="parmacy" class="form-control" id="parmacy" name = "parmacy" placeholder="주로 방문하는 약국이나 병원을 입력해주세요">
          </div>
        
        <br/>
          <hr class="mb-4">
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="aggrement" required>
            <label class="custom-control-label" for="aggrement">개인정보 수집 및 이용에 동의합니다.</label>
          </div>
          <div class="mb-4"></div>
          <div class="mb-3" style="float:left; margin-right:30px">
            <button id="btn-1" class="btn btn-primary btn-lg btn-block" type="submit" style="background-color: #b0ddb6; width:150px;" style="background-color: rgba(117, 117, 117, 0.5); width:150px;">가입 완료</button></div>
          <div class="mb-3" style="float:left;">
            <button id="btn-1" class="btn btn-primary btn-lg btn-block" type="button" onclick = "location.href= '{% url 'member:login' %}'" style="background-color: rgba(117, 117, 117, 0.5); width:150px;">취소</button></div>
        </form>
      </div>
    </div>


    <footer class="my-3 text-center text-small">
      <p class="mb-1">&copy; Medipenser</p>
    </footer>
  </div>
  <script>
    window.addEventListener('load', () => {
      const forms = document.getElementsByClassName('validation-form');

      Array.prototype.filter.call(forms, (form) => {
        form.addEventListener('submit', function (event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }

          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  </script>
</body>

</html>