cam/urls.py
from django.conf import settings
from django.urls import path
from cam.views import camera_1,md,cap,Register,operation
from django.conf.urls.static import static


app_name='cam'

urlpatterns = [
    path('show/',camera_1,name='show'),
    path('cap/',cap,name='cap'),
    path('input/',Register,name='Register'),
    path('mod/',md,name='mod'),
    path('operation/',operation,name='operation'),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cam/', include('cam.urls')),
    path('', include('main.urls')),
    path('contact/', include('contact.urls')),
    path('member/', include('member.urls')),
]

contact/urls.py
from django.conf import settings
from django.urls import path
from contact.views import contact, search, detail
from contact.views import update, delete, answer_create, answer_delete
from contact.views import upload3, download
from django.conf.urls.static import static

app_name='contact'

urlpatterns = [
    path('contact/', contact, name="list"),
    path('search/', search, name='search'),
    path('<int:question_id>/', detail, name='detail'),
    path(
        'answer/create/<int:question_id>/', answer_create,
        name='answer_create'),
    path('<int:question_id>/update/', update, name="update"),
    path('<int:question_id>/delete/', delete, name="delete"),
    path('upload3/', upload3, name='upload3'),
    path('download/<int:question_id>/', download, name='download'),
    path('<int:answer_id>/answer_delete/', answer_delete, name="answer_delete"),
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

firebase/firebase/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main/urls.py
from django.conf import settings
from django.urls import path
from main.views import index,about,chatanswer
from django.conf.urls.static import static

app_name='main'

urlpatterns = [
    path('',index,name='index'),
    path('about/',about,name='about'),
    path('chatanswer/', chatanswer, name="chatanswer")
]+ static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

main/models.py
# from django.db import models

# Create your models here.

main/views.py
import json
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
from tensorflow import keras
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
import numpy as np
from django.http import JsonResponse


def index(request):
    context={}
    return render(request, 'main/index.html',context)
   
def about(request):
    return render(request, 'main/about.html')


@csrf_exempt
def chatanswer(request):
    context = {}

    questext = request.GET['questext']
    import pickle

    file = open("./model/intents.json", encoding="UTF-8")
    data = json.loads(file.read())

    def chat3(inp):
        # load trained model
        model = keras.models.load_model('model/chat_model.h5')

        # load tokenizer object
        with open('model/tokenizer.pickle', 'rb') as handle:
            tokenizer = pickle.load(handle)

        # load label encoder object
        with open('model/label_encoder.pickle', 'rb') as enc:
            lbl_encoder = pickle.load(enc)

        # parameters
        max_len = 50

        # while True:
        print("User: ", end="")

        result = model.predict(keras.preprocessing.sequence.pad_sequences(tokenizer.texts_to_sequences([inp]),
                                                                          truncating='post', maxlen=max_len))
        tag = lbl_encoder.inverse_transform([np.argmax(result)])
        for i in data['intents']:
            if i['tag'] == tag:
                txt1 = np.random.choice(i['responses'])
                print("ChatBot:" , txt1)

        return txt1

    anstext = chat3(questext)
    print(anstext)

    context['anstext'] = anstext
    context['flag'] = '0'

    return JsonResponse(context, content_type="application/json")

main/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,700|Crimson+Text:400,400i" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
  
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  
  
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
  
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
  </head>

<body>

  <div class="site-wrap">
    <div class="site-navbar py-2">

      <div class="search-wrap">
        <div class="container">
          <a href="#" class="search-close js-search-close"><span class="icon-close2"></span></a>
          <form action="#" method="post">
            <input type="text" class="form-control" placeholder="Search keyword and hit enter...">
          </form>
        </div>
      </div>

      <div class="container">
        <div class="d-flex align-items-center justify-content-between">
          <div class="logo">
            <div class="site-logo">
              <a href="{% url 'main:index' %}" class="js-logo-clone"><img src="{% static 'images/logo1.png' %}" width='200'></a>
            </div>
          </div>
          <div class="main-nav d-none d-lg-block">
            <nav class="site-navigation text-right text-md-center" role="navigation">
              <ul class="site-menu js-clone-nav d-none d-lg-block">
                <li><a href="{% url 'main:index' %}">Home</a></li>
                <li><a href="{% url 'cam:show' %}">Camera</a></li>
                <li><a href="{% url 'main:about' %}">UserPage</a></li>
                <li class="active"><a href="{% url 'main:contact' %}">Contact</a></li>
                <li><a href="login.html">Logout</a></li>
              </ul>
            </nav>
          </div>
          <div class="icons">
            <a href="#" class="site-menu-toggle js-menu-toggle ml-3 d-inline-block d-lg-none"><span
                class="icon-menu"></span></a>
          </div>
        </div>
      </div>
    </div> 

<!--네비게이션 END -->

        <!-- 기본 템플릿 안에 삽입될 내용 Start -->
        {% block content %}

        {% endblock %}
        <!-- 기본 템플릿 안에 삽입될 내용 End -->


<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
      
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>